### PR TITLE
Fix typos in appd.yml

### PR DESCRIPTION
**Pull request by RichLinnell**
Fixed a few typos in the interface definition.

### CODE REVIEW

**Comment by finos-admin** [comment]
Thank you for your pull request and welcome to our community! We require contributors to sign a [Contributor License Agreement](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement) and we don't seem to have CLAs on file for these contributors to the Pull Request: (@richlinnell). In order for your PR to be reviewed and merged, please follow the directions at the link above.

Project team: please **do not merge this Pull Request** until Foundation staff have confirmed that a CLA is in place for the new contributor(s) listed above.

If there are any questions, please don't hesitate to [get in touch with our Infrastructure Support team](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/77955298/Getting+in+Touch#GettinginTouch-InfrastructureSupport). /CC @finos-admin

**Comment by RichLinnell** [comment]
I'm pretty sure that we have CLA's in place, please check with Espen Overbye.

**Comment by maoo** [comment]
Dear @RichLinnell , thanks for your contribution! The [Contributor License Agreement](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement) that is mentioned above is a requirement to contribute to [FINOS, the Fintech Open Source Foundation](finos.org) (which FDC3 is part of, since April 24 2018) and we don't seem to have received any signed agreement from you (Individual agreement) or Adaptive (Corporate agreement).

Could you please follow the documentation and reach out to [help@finos.org](mailto:help@finos.org) for any question? This will instruct our CLA bot to approve your Pull Requests from a legal standpoint, across all our programs and activities; you can check [finos.github.io](http://finos.github.io/) for a full overview.

Thanks!

**Comment by copiesofcopies** [comment]
Hi @RichLinnell, do you mean that Adaptive has a CLA in place with FINOS, or that you are working on behalf of OpenFin and they have a CLA in place with us?

**Pull request merged**
