### PR TITLE
Update swagger 2.0 to open-api 3.0.0

### PR DESCRIPTION
**Pull request by ggeorgievx**
version: 0.0.2

Tick42

### CODE REVIEW

**Comment by finos-admin** [comment]
Thank you for your pull request and welcome to our community! We require contributors to sign a [Contributor License Agreement](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement) and we don't seem to have CLAs on file for these contributors to the Pull Request: (@ggeorgievx). In order for your PR to be reviewed and merged, please follow the directions at the link above.

Project team: please **do not merge this Pull Request** until Foundation staff have confirmed that a CLA is in place for the new contributor(s) listed above.

If there are any questions, please don't hesitate to [get in touch with our Infrastructure Support team](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/77955298/Getting+in+Touch#GettinginTouch-InfrastructureSupport). /CC @finos-admin

**Comment by ftbb** [comment]
The problem with the spec being 3.0.0 is that swagger-gen doesn't fully support it yet.  Let me investigate a bit, but would suggest you create a new file called appd_openapi.yaml and keep both in sync (logical).

**Comment by ggeorgievx** [comment]
We created a new pull request (https://github.com/FDC3/appd-api/pull/3) that contains the required changes to support open-api-3.

**Comment by ftbb** [comment]
https://github.com/FDC3/appd-api/pull/3 supersedes

**Pull request closed without merging**
